function [y] = sp_sym_grad_3_3(x,Dx,Dy,Dz,dx,dy,dz)

[n,m,t,k] = size(x);
N = n*m*t;

y = reshape( [ 	  (Dx*reshape(x(:,:,:,1),N,1))/dx ;...
                  (Dy*reshape(x(:,:,:,2),N,1))/dy ;...
                  (Dz*reshape(x(:,:,:,3),N,1))/dz ;...
                  ...
          (Dy*reshape(x(:,:,:,1),N,1))/(2*dy) +  (Dx*reshape(x(:,:,:,2),N,1))/(2*dx)	;...
		  (Dz*reshape(x(:,:,:,1),N,1))/(2*dz) +  (Dx*reshape(x(:,:,:,3),N,1))/(2*dx)	;...
		  (Dz*reshape(x(:,:,:,2),N,1))/(2*dz) +  (Dy*reshape(x(:,:,:,3),N,1))/(2*dy) ] , n,m,t,6 );